version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fardlab12345
      POSTGRES_USER: mkhfring
      POSTGRES_DB: fardlabdb
    ports:
      - 5432:5432

