version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 5001:5001
    environment:
      - FLASK_APP=flasker:create_app

  
  my-angular-app:
    build: ../lab-website/
    ports:
      - "3000:3000"
